# Generated by Django 3.0.6 on 2020-05-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggeduser',
            name='perfil_image',
            field=models.CharField(default='', max_length=300),
        ),
    ]
