# Generated by Django 3.0.6 on 2020-05-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_loggeduser_perfil_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggeduser',
            name='logged_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
