# Generated by Django 3.0.6 on 2020-05-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200521_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='loggeduser',
            name='room_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
